// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: common/v1/types.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          UserRole               `protobuf:"varint,2,opt,name=role,proto3,enum=common.v1.UserRole" json:"role,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserContext) Reset() {
	*x = UserContext{}
	mi := &file_common_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserContext) ProtoMessage() {}

func (x *UserContext) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserContext.ProtoReflect.Descriptor instead.
func (*UserContext) Descriptor() ([]byte, []int) {
	return file_common_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *UserContext) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserContext) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_USER_ROLE_UNSPECIFIED
}

func (x *UserContext) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_common_v1_types_proto protoreflect.FileDescriptor

const file_common_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x15common/v1/types.proto\x12\tcommon.v1\x1a\x15common/v1/enums.proto\"\\\n" +
	"\vUserContext\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x04role\x18\x02 \x01(\x0e2\x13.common.v1.UserRoleR\x04role\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05emailB.Z,github.com/Animesh-na/shared_proto/common/v1b\x06proto3"

var (
	file_common_v1_types_proto_rawDescOnce sync.Once
	file_common_v1_types_proto_rawDescData []byte
)

func file_common_v1_types_proto_rawDescGZIP() []byte {
	file_common_v1_types_proto_rawDescOnce.Do(func() {
		file_common_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_types_proto_rawDesc), len(file_common_v1_types_proto_rawDesc)))
	})
	return file_common_v1_types_proto_rawDescData
}

var file_common_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v1_types_proto_goTypes = []any{
	(*UserContext)(nil), // 0: common.v1.UserContext
	(UserRole)(0),       // 1: common.v1.UserRole
}
var file_common_v1_types_proto_depIdxs = []int32{
	1, // 0: common.v1.UserContext.role:type_name -> common.v1.UserRole
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_v1_types_proto_init() }
func file_common_v1_types_proto_init() {
	if File_common_v1_types_proto != nil {
		return
	}
	file_common_v1_enums_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_types_proto_rawDesc), len(file_common_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_types_proto_goTypes,
		DependencyIndexes: file_common_v1_types_proto_depIdxs,
		MessageInfos:      file_common_v1_types_proto_msgTypes,
	}.Build()
	File_common_v1_types_proto = out.File
	file_common_v1_types_proto_goTypes = nil
	file_common_v1_types_proto_depIdxs = nil
}
